database:
  url: "postgres://champ001:123champ123@localhost:5432/mydatabase?sslmode=disable"

data_generation:
  num_chats: 5000
  num_clients: 10000
  num_orders: 50000
  num_messages: 25000
  num_promo_codes: 1000
  num_couriers: 2000
  num_support_staffs: 1000
  num_rates: 500

